### ISSUE TITLE
Upgrading to Manifest V3

### ISSUE THREAD

**Issue by Rutuj-Runwal** [swarajp486/PenTab#1]
Manifest V3 is the new standard for browser extensions.
We can update this extension to Manifest V3.

The permissions listed below will be more or less the same but will need to update the background scripts to service workers.

`"permissions": [
    "activeTab",
    "storage",
    "scripting"
  ]`

Also the onclicked listener event in `background.js` is not required as it is making it difficult to close the popup in the current implementation:
```
chrome.browserAction.onClicked.addListener(buttonclick)
function buttonclick(tab){
    console.log(tab)
    let msg={
        txt: "hello"
    }
    chrome.tabs.sendMessage(tab.id,msg)
}
```

**Comment by swarajp486** [comment]
Yes we can upgrade to MV3.
Good observation, that the background.js is stuck and the popup cannot be closed. I found the same behavior in my testing.

Go ahead with it.
